osx_image: xcode7.3
sudo: required
dist: trusty

language: c

git:
  depth: 3

branches:
  only:
    - master
    - dev

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
    - os: osx

before_script:
 - chmod +x ./script/travis-build.sh
 - chmod +x ./script/build_ml.sh
 - export NODE_VERSION=$(cat .node-version)
 - export TEST_RUN=true

script: ./script/travis-build.sh

after_success:
  - node_modules/.bin/gulp coverage
  - npm run coveralls
  - npm run codeclimate
  - lgcm=$(git log -1 --pretty=%B | xargs echo);
    if [[ $lgcm == *"[build]"* ]]; then
      ./script/build_ml.sh;
    fi

cache:
  apt: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - xvfb
